services:
  web:
    image: cosmo-nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80

networks:
  default:
    name: cosmonaut_proxy
    external: true
